spring:
  profiles:
    active: local
   
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
         
server:
  port: 8080
    
cloud:
  aws:
    s3:
      bucket: sshj
    region:
      static: ap-northeast-2
    stack:
      auto: false
