spring:
  profiles:
    active: dev
   
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    
cloud:
  aws:
    s3:
      bucket: sshj
    region:
      static: ap-northeast-2
    stack:
      auto: false
---
spring:
  profiles: local
   
  redis:
    host: localhost
    port: 6379

server:
  port: 9090
---
spring:
  profiles: dev
    
  redis:
    host: elc-sshj-0001-001.bxl8mx.0001.apn2.cache.amazonaws.com
    port: 6379

server:
  port: 8080