spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://sshj.chmntjt5idfk.ap-northeast-2.rds.amazonaws.com:3306/sshj?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: daedo
    password: eo!eh2zm3fn4
    
cloud:
  aws:
    s3:
      bucket: sshj
    region:
      static: ap-northeast-2
    stack:
      auto: false