spring:
  profiles:
    active: local

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://sshg.chmntjt5idfk.ap-northeast-2.rds.amazonaws.com:3306/sshg?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
      username: admin
      password: eo!eh2zm3fn4