spring:
  jpa:
    database: mysql
    show-sql: true
  profiles:
    active: local
   
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    url: jdbc:mysql://localhost:3306/sshj?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 4531
    driver-class-name: com.mysql.cj.jdbc.Driver

cloud:
  aws:
    s3:
      bucket: sshj
    region:
      static: ap-northeast-2
    stack:
      auto: false


---
spring:
  profiles: local
   
  redis:
      host: localhost
      port: 6379

server:
  port: 9090
---
spring:
  profiles: dev

  redis:
      host: localhost
      port: 7379

#  추후 aws Redis 클러스터 사용할때 적용    
#  redis:
#    host: elc-sshj.bxl8mx.clustercfg.apn2.cache.amazonaws.com
#    port: 6379

server:
  port: 8080